%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/henrik/Documents/umu/CFD/lab2/Q4_data/9_Lab2_Pkplus_DNS_Retau395_Kim_etal_211028_1.txt
%
% Auto-generated by MATLAB on 24-Nov-2021 23:30:31

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["y", "Prod"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Lab2PkplusDNSRetau395Kimetal2110281 = readtable("/home/henrik/Documents/umu/CFD/lab2/Q4_data/9_Lab2_Pkplus_DNS_Retau395_Kim_etal_211028_1.txt", opts);

%% Convert to output type
DNS_table = table2array(Lab2PkplusDNSRetau395Kimetal2110281);

%% Clear temporary variables
clear opts